### ISSUE TITLE
"No implicit conversion of Symbol into String"

### ISSUE THREAD

**Issue by peterlupu** [mrmans0n/localio#13]
Hi,

Keep in mind that I have no experience with ruby, I'm just trying to generate translation files for my iOS app.

My Locfile uses a basic xlsx source:

```
platform :ios

output_path :'/absolute/path/to/project/'

source  :xlsx,
        :path => 'Strings.xlsx'

formatting :smart
```

When I run `localize`, I get:

```
Languages detected: en, ru, zh, fr, es, ar, pt, ja -- using en as default.
Building terminology in memory...
Loaded!
Writing iOS translations...
no implicit conversion of Symbol into String
```

So I've started debugging and I've changed the following in `localio/writers/ios_writer.rb`:

> languages.keys.each do |lang|
>       output_path = File.join(path**.to_s**, "#{lang}.lproj/")

and

> if create_constants && !constant_segments.nil?
>       TemplateHandler.process_template 'ios_constant_localizable.erb', path**.to_s**, 'LocalizableConstants.h', constant_segments
>       puts ' > ' + 'LocalizableConstants.h'.yellow
>     end

And now the I've successfully generated my files.

Question is: is my Locfile wrong? Is this an actual bug in the gem?

Thank you,
Peter

**Comment by mrmans0n** [comment]
Just remove the : in output_path. 

Your Locfile should look like this:
```ruby
platform :ios

output_path '/absolute/path/to/project/'

source  :xlsx,
        :path => 'Strings.xlsx'

formatting :smart
```

That colon is making the string to be a symbol, which is what triggers the error.

**Comment by peterlupu** [comment]
Thank you, this solved it.
