### ISSUE TITLE
issue while localizing

### ISSUE THREAD

**Issue by andreacremaschi** [mrmans0n/localio#15]
Hi!
I found your project and it seems really interesting to me, but I have some issues making it work..
I prepared the following Locfile:

```
platform :ios

source :xls, :path => 'traduzioni.xls'
output_path 'sterilizzatrici/Localizables/'

formatting :smart 
```

and when I call ```localize``` it fails with this error message:

```
Languages detected: it, en, fr, de -- using en as default.
Building terminology in memory...
Loaded!
Writing iOS translations...
 > it
undefined method `replace_escaped' for nil:NilClass
```

Any idea what's going on? I am using 

```ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]```

and 

```
localio (0.0.23)
```

**Comment by mrmans0n** [comment]
Hi Andrea.

Could by any chance any of your lines have a ' character without escaping? If so, please escape it like this \'

**Comment by andreacremaschi** [comment]
hi,
thank you for the hint, it didn't solve my issue yet, but I tried leaving just one row and now the script completes without issues. It seems to be an escaping issue in my file
:beer:

**Comment by andreacremaschi** [comment]
Ok, I've got it: I had some blank values in my spreadsheet and localio doesn't like it. Apart from this the .strings files are correct. Maybe this should be better documented? Thank for the great project!
