### ISSUE TITLE
Build error when selecting swift platform

### ISSUE THREAD

**Issue by luismacb** [mrmans0n/localio#18]
In Xcode 6.4 & iOS 8, the generated file "LocalizableConstants.swift" doesn't compile.

I was going to submit a PR myself, but I don't have credentials. To fix this, you only need to add "import Foundation" to the "swift_constant_localizable.erb" template.

**Comment by mrmans0n** [comment]
You don't need credentials, just fork the repo, fix it in your forked repo, and submit a PR from there. That's the magic of GitHub! :smile:
