### ISSUE TITLE
The conversion changes [key]'s upper case into lower cases

### ISSUE THREAD

**Issue by Pennylele** [mrmans0n/localio#37]
Example excel sheet: http://prntscr.com/iob5yx
Converted Android key: http://prntscr.com/iob6be

Can we maintain the uppercase letters?

**Comment by mrmans0n** [comment]
If you add to your localio file

`formatting :none`

the keys will be preserved. For different approaches, check the readme and look for "formatting" types.

**Comment by Pennylele** [comment]
Thanks a lot, Nacho! It works perfectly for me!
Since I don't have access to the Android and iOS platform (but only doing the conversion), based on the instructions in ReadMe file, the default formatting (formatting :smart) would be good enough for Android and iOS - is that the case? I thought both platform would be case-sensitive though? But I could be wrong..
